image: Ubuntu

stack: jdk11

branches:
only:
  - master

build: off

install:

  java -jar ./artifacts/app-card-delivery.jar &
  chmod +x ./gradlew
build_script:

  ./gradlew test --info -Dselenide.headless=true